# This is a workflow that automatically runs tests when pushing to the repo.  
# If the tests are successful, the project is deployed to Heroku.

name: Deploy to Heroku

on: [push, pull_request]

jobs:

  package:
    name: Maven Package (no tests) 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Kotlin
          uses: fwilhe2/setup-kotlin@0.2.0
          with:
            version: 1.3.72
      - name: Maven Package
        run: mvn -B clean package -DskipTests

  test:
    name: Maven Tests
    needs: package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Verify
        run: mvn -B clean verify

  deploy:
   name: Deploying to Heroku
   needs: test
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v2
    - uses: AkhileshNS/heroku-deploy@v3.5.7
      name: Deploy to Heroku
      with:
        # This will be used for authentication. You can find it in your heroku homepage account setting
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        # Email that you use with heroku
        heroku_email: 20075835@mail.wit.ie
        # The appname to use for deploying/updating
        heroku_app_name: health-tracker-5835-staging
        # A URL to which a healthcheck is performed (checks for 200 request)
        healthcheck: https://health-tracker-5835-staging.herokuapp.com/
